version: '3.1'
services:
  savetherecipe:
    image: ghcr.io/vladimirgolovanov/savetherecipe/savetherecipe:latest
    build:
      dockerfile: docker/Dockerfile
    container_name: savetherecipe
    working_dir: /app
    env_file:
      - path: .env
        required: false
    ports:
      - '44045:8080'
    networks:
      - grpc-net
    restart: unless-stopped

networks:
  grpc-net:
    external: true
